# Generated by Django 3.2.23 on 2024-02-13 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20240213_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='buyer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_details', to='account.userdata'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='seller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_details', to='account.userdata'),
        ),
    ]
