# Generated by Django 3.2.23 on 2024-02-13 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20240213_0621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='seller',
        ),
    ]
