# Generated by Django 3.2.23 on 2024-02-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20240213_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='password_reset_token_generated_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
