# Generated by Django 5.0.2 on 2024-02-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_userdetails_password_reset_token_generated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='is_buyer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
