# Generated by Django 5.0.2 on 2024-02-13 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_userdetails_is_buyer_userdetails_is_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='is_buyer',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='is_seller',
        ),
    ]
