# Generated by Django 5.0.2 on 2024-02-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_remove_userdetails_is_buyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='is_buyer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
